blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^category/(?P<cat>.*)$', views.blog_list, name='blog_post_list_cat'),
    url(r'^tag/(?P<tag>.*)$', views.blog_list, name='blog_post_list_tag'),
    url(r'^archive/year/(?P<year>\d{4})/month/(?P<month>\d{1,2})$',
        views.blog_list, name='blog_post_list_year_month'),
    url(r'^archive/year/(?P<year>\d{4})$', views.blog_list,
        name='blog_post_list_year'),
    url(r'^post/(?P<slug>.*)/$', views.single_post, name='blog_single'),
    url(r'^$', views.blog_list, name="blog_post_list"),
]

home/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.sitemaps.views import sitemap

from solid_i18n.urls import solid_i18n_patterns

from home.sitemaps import PagesSitemap, StaticSitemap, BlogSitemap


sitemaps = {
    'pages': PagesSitemap(),
    'static': StaticSitemap(),
    'blog': BlogSitemap(),
}
urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^secureadmin/', admin.site.urls),
    url(r'^redactor/', include('redactor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^rosetta/', include('rosetta.urls')),
    )

urlpatterns += solid_i18n_patterns(
    url(r'^account/', include('account.urls')),
    url(r'^financial/', include('financial.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^support/', include('tickets.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^', include('index.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
)

blog/models.py
from django.contrib.sitemaps import ping_google
from django.db import models
from django.utils.text import slugify
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from redactor.fields import RedactorField


class Author(models.Model):
    # Display_name should be available for translation
    user = models.OneToOneField(User, related_name='author')
    display_name = models.CharField(max_length=128)
    avatar = models.ImageField(upload_to='authors/', blank=True)

    class Meta:
        verbose_name = _("Author")
        verbose_name_plural = _("Authors")

    def __unicode__(self, *args, **kwargs):
        return self.display_name


class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(blank=True, unique=True)

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')

    def save(self, *args, **kwargs):
        # if not self.id:
        #     self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        # return "%s , %s" % (self.name, self.slug)
        return self.name

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('blog_post_list_cat', args=[str(self.slug)])


class Tag(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(blank=True)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

    def save(self, *args, **kwargs):
        # if not self.id:
        #     self.slug = slugify(self.name)
        super(Tag, self).save(*args, **kwargs)

    def __unicode__(self):
        # return "%s , %s" % (self.name, self.slug)
        return self.name

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('blog_post_list_tag', args=[str(self.slug)])


# editor added for body in post, more information
# in : github.com/douglasmiranda/django-wysiwyg-redactor
class Post(models.Model):
    header = models.ImageField(upload_to='headers/')
    title = models.CharField(max_length=255)
    slug = models.SlugField(blank=True)

    body = RedactorField()
    seo_abs = models.TextField(blank=True)

    cat = models.ManyToManyField(Category)
    tag = models.ManyToManyField(Tag)

    publish = models.BooleanField(default=True)
    comments_off = models.BooleanField(default=True)

    lang = models.CharField(max_length=2, choices=settings.LANGUAGES,
                            default='en', verbose_name=_('Language'))

    author = models.ForeignKey(Author, editable=False)
    viewed = models.PositiveIntegerField(
        verbose_name=_('Views'), default=0, editable=False
    )

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

        if self.publish:
            self.call_google()

    @staticmethod
    def call_google():
        try:
            ping_google()
        except Exception:
            # Bare 'except' because we could get a variety
            # of HTTP-related exceptions.
            pass

    def __unicode__(self):
        return "%s" % self.title

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('blog_single', args=[str(self.slug)])

    def get_tags(self):
        T = self.tag.all()
        return ', '.join(t.name for t in T)
    get_tags.short_description = 'Tag (s)'

    def get_cat(self):
        C = self.cat.all()
        return ', '.join(c.name for c in C)
    get_cat.short_description = 'Category'

    def incr_view(self):
        self.viewed += 1
        self.save()


class Comment(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    website = models.URLField(blank=True)
    post = models.ForeignKey(Post, related_name='comments')
    body = models.TextField()

    date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = _("Comment")
        verbose_name_plural = _("Comments")

    def __unicode__(self):
        # return "%s, %s" % (self.name, self.body)
        return self.name

services/InstagramData/models.py
from __future__ import unicode_literals

import pytz
from constance import config
from django.db import models
from django.utils import timezone
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _


class User(models.Model):
    id = models.BigIntegerField(primary_key=True)
    username = models.CharField(max_length=255)
    bio = models.CharField(max_length=255, blank=True, null=True)
    website = models.URLField(blank=True, null=True)
    profile_picture = models.URLField(blank=True, null=True)
    full_name = models.CharField(max_length=255, blank=True, null=True)

    access_token = models.CharField(max_length=255, blank=True, null=True)
    added = models.DateTimeField(default=timezone.now, editable=False)
    modified = models.DateTimeField(default=timezone.now, editable=False)

    media = models.CharField(max_length=50,
                             verbose_name='Media at register time', blank=True,
                             null=True)
    followed_by = models.CharField(max_length=50,
                                   verbose_name='Followers at startup',
                                   blank=True, null=True)
    follows = models.CharField(max_length=50,
                               verbose_name='Following at startup', blank=True,
                               null=True)
    is_business = models.BooleanField(verbose_name='Is business', default=False)
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-added']
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def __unicode__(self):
        return self.username

    @property
    def is_free(self):
        return int(self.followed_by) < config.INSTAGRAM_FREE_LEVEL_MAX_FOLLOWERS

    def change_last_update(self, time):
        self.last_update = time
        self.save()

    @classmethod
    def add_or_update_user(cls, data):
        id = data.pop('id')
        user, result = cls.objects.update_or_create(id=id, defaults=data)
        return user


class Tag(models.Model):
    name = models.CharField(max_length=255)
    media_count = models.IntegerField(null=True, blank=True)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')

    def __unicode__(self):
        return self.name

    @classmethod
    def add_or_update(cls, name, dic):
        del dic['name']
        tag, result = Tag.objects.update_or_create(name=name, defaults=dic)
        return tag


class Location(models.Model):
    id = models.BigIntegerField(primary_key=True)
    latitude = models.CharField(max_length=50, blank=True, null=True)
    longitude = models.CharField(max_length=50, blank=True, null=True)
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name = _('Location')
        verbose_name_plural = _('Locations')

    def __unicode__(self):
        return self.name

    @classmethod
    def add_or_update(cls, data):
        id = data['id']
        del data['id']
        location, result = cls.objects.update_or_create(id=id, defaults=data)
        return location


class Comment(models.Model):
    id = models.BigIntegerField(primary_key=True)
    user = models.ForeignKey(User)
    text = models.TextField()
    created_at = models.DateTimeField()

    class Meta:
        verbose_name = _('Comment')
        verbose_name_plural = _('Comments')

    def __unicode__(self):
        return '%s said : %s' % (unicode(self.user), self.text)

    def save(self, *args, **kwargs):
        self.created_at = pytz.utc.localize(self.created_at)
        super(Comment, self).save(*args, **kwargs)

    @classmethod
    def store(cls, id, data):
        del data['id']
        comment, result = cls.objects.update_or_create(id=id, defaults=data)
        return comment


class Image(models.Model):
    low_resolution = models.URLField()
    thumbnail = models.URLField()
    standard_resolution = models.URLField()

    class Meta:
        verbose_name = _('Image')
        verbose_name_plural = _('Images')

    def __unicode__(self):
        return unicode(self.id)

    @classmethod
    def save_image(cls, dic):
        image, result = Image.objects.get_or_create(**dic)
        return image

    def image(self):
        return format_html('<img src="{}" style="height: 50px;width: 50px;"/>',
                           self.thumbnail)


class Video(models.Model):
    low_resolution = models.URLField()
    low_bandwidth = models.URLField()
    standard_resolution = models.URLField()

    class Meta:
        verbose_name = _('Video')
        verbose_name_plural = _('Videos')

    def __unicode__(self):
        return unicode(self.id)


class Media(models.Model):
    insta_id = models.CharField(max_length=255, null=True)
    attribution = models.CharField(max_length=50, null=True, blank=True)
    type = models.CharField(max_length=50)
    location = models.ForeignKey(Location, related_name='media_location',
                                 null=True, blank=True)
    filter = models.CharField(max_length=50, null=True, blank=True)
    created_time = models.DateTimeField()
    link = models.URLField()
    like_count = models.IntegerField(null=True, blank=True,
                                     verbose_name='likes')
    images = models.ForeignKey(Image, related_name='media_images')
    caption = models.ForeignKey(Comment, related_name='Media_Caption',
                                blank=True, null=True)
    videos = models.ForeignKey(Video, verbose_name='media_videos', blank=True,
                               null=True)
    user_has_liked = models.BooleanField(default=False)
    user = models.ForeignKey(User, related_name='posted_media')
    comment_count = models.IntegerField(verbose_name='Comments count',
                                        blank=True, null=True)
    hashtags = models.ManyToManyField(Tag, verbose_name='Hashtags',
                                      related_name='media')
    comments = models.ManyToManyField(Comment, verbose_name='Comments',
                                      related_name='media')
    tagged_users = models.ManyToManyField(User, verbose_name='Tagged users',
                                          related_name='tagged_media')

    imported_at = models.DateTimeField(auto_now=True)
    modified_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _('Media')
        verbose_name_plural = _('Medias')

    def __unicode__(self):
        return unicode(self.id)

    def show_caption(self):
        return self.caption.text

    def save(self, *args, **kwargs):
        self.created_time = pytz.utc.localize(self.created_time)
        super(Media, self).save(*args, **kwargs)

index/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfile
from django.utils.translation import ugettext_lazy as _


class UserForm(forms.ModelForm):
    password = forms.CharField(label=_('Password'),
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': _('Password')}))
    fullname = forms.CharField(label=_('Full Name'),
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Full Name')}))

    # def clean(self):
    # 	password = self.cleaned_data.get('password')
    # 	confirm_password = self.cleaned_data.get('confirm_password')

    # 	if password and password != confirm_password:
    # 		raise forms.ValidationError(_("Passwords don't match, please try again"))

    # 	return self.cleaned_data

    class Meta:
        model = User
        fields = ('fullname', 'username', 'email', 'password')
        widgets = {
            # 'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            # 'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Username')}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': _('Email')}),
        }

    error_messages = {
        'password': {
            'max_length': _("Passwords don't match, please try again"),
        },
    }


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'mobile', 'profile_pic')
        widgets = {
            'website': forms.URLInput(attrs={'class': 'form-control'}),
            'mobile': forms.TextInput(attrs={'class': 'form-control'})
        }

services/InstagramData/views.py
from django.shortcuts import render

# Create your views here.

services/graph_api/views.py
from django.shortcuts import render

# Create your views here.

templates/index/base.html
<!doctype html>
{% load analytical %}
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html>
<!--<![endif]-->
<head>
	{% analytical_head_top %}
	{% load staticfiles %}
	{% load i18n %}
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% block meta%}{% endblock %}
	{% block title %}{% endblock %}
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'index/css/style.css' %}">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	{% block css %}{% endblock %}
	<!-- RTL setting -->
	{% get_current_language_bidi as bidi %}
	{% if bidi %}
	<!-- link href='{% static "index/css/RTL.css" %}' rel="stylesheet" /-->
	{% endif %}
	{% analytical_head_bottom %}
</head>
<body>
{% analytical_body_top %}
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

{% include 'index/nav_bar_header.html' %}

{% block content %}{% endblock %}

{% include 'index/footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
  function validateSubscribeEmail() {
  var email= document.getElementById("subscribe-email").value;
  var csrftoken = Cookies.get('csrftoken');
  $.ajax({
          type:"GET",
          url:'/account/newsletter/subscribe/',
          data:{email:email},
          success:function(responsedata){
            document.getElementById("subscribe-message").innerHTML = responsedata.message;
          }
       })
  }

</script>
{% block js %}{% endblock %}
{% analytical_body_bottom %}
</body>
</html>

templates/index/demo.html
{% extends 'index/base.html' %}
{% load i18n %}
{% block title %}
    <title>{% trans 'Professional Instagram Analyzer • InProbes' %}</title>
{% endblock %}
{% load staticfiles %}
{% block meta%}
    <meta name="description" content="{% blocktrans %}Analyze your Instagram account like professionals, manage Instagram campaigns and get dipper inside your audiences statistics{% endblocktrans %}">
    <meta property="og:title" content='{% trans "InProbes • Login" %}' />
    <meta property="og:description" content="{% blocktrans %}Analyze your Instagram account like professionals, manage Instagram campaigns and get dipper inside your audiences statistics{% endblocktrans %}" />
    <meta property="og:image" content="https://inprobes.com/static/index/img/logo/social.png" />
    <meta name="keywords" content="Professional Instagram account analyzer, hold or manage campaigns with specific hashtags, audiences statistics">
{% endblock %}
{% block content %}
{% load i18n %}
<div class="main-container">
    <div class="main wrapper clearfix">
      <div class="main-page">
        <center>
          <div class="inprobes-typo-small">
            <img src='{% static "index/image/inprobes-2color.png" %}' alt="inprobes">
          </div>
            <p style="margin-top:30px; padding: 0px 200px;">
                اینپروبز سرویس‌های متنوعی رو ارایه میده که برای دیدن لیست کامل و توضیحات بیشتر میتونید <a href="#">این صفحه</a> رو ببینید. لیست پکیج‌های متنوع ارتقا حساب کاربری هم در دسترس قرار داره که از <a href="#">این لینک</a> میتونید مشاهده کنید و اکانت خودتون رو ارتقا بدید.
اگر حس میکنید باید قبل از اقدام به خرید، سرویس رو تست کنید یا برای استفاده از سرویس‌های ما توی شرکت/سازمان/استارتاپ خودتون نیاز به مشاوره دارید کافیه که با demo@inprobes.com مکاتبه کنید تا ما یک اکانت تست براتون بسازیم یا توی پیدا کردن سرویس و پیکیج مناسب کمکتون کنیم.
            </p>
        </center>
      </div>
    </div>
</div>
{% endblock %}

templates/index/en_privacy.html
{% extends 'index/base.html' %}
{% load i18n %}
{% block title %}
<title>Privacy policy • Inprobes</title>
{% endblock %}
{% block meta%}
<meta name="description" content="{% blocktrans %}Analyze your Instagram account like professionals, manage Instagram campaigns and get dipper inside your audiences statistics{% endblocktrans %}">
<meta property="og:title" content='{% trans "InProbes • context.title" %}'/>
<meta property="og:description" content="{% blocktrans %}Analyze your Instagram account like professionals, manage Instagram campaigns and get dipper inside your audiences statistics{% endblocktrans %}"/>
<meta property="og:image" content="https://inprobes.com/static/index/img/logo/social.png"/>
<meta name="keywords" content="Professional Instagram account analyzer, hold or manage campaigns with specific hashtags, audiences statistics">
{% endblock %}
{% block content %}
<section>
	<br>
	<div class="container">
		<div class="row">
			<br><br>
			<div class="col-md-2 col-xs-1 col-sm-1"></div>
			<div class="col-md-8 col-xs-10 col-sm-10">
				<h3>Privacy Policy</h3>
				<br><br>
				An important basis for the design InProbes , Care of the user's personal informationand this can be seen in all the services offered site.it should be noted all of privacy policy of
				InProbes are subset of Instagram privacy policy and this site will be according to the Islamic Republic Iran. All Privacy Policy to use of InProbes , is as follow :

				1. Information collection and use

				1.1 information such as name ,family , email ,…that you enter when register on site ,just to provide unique services to you

				1.2 From time to time, we may ask for and gather additional information from you.

				1.3 All process of add Instagram account will be done by API and InProbes have no information of your password.

				1.4 InProbes have no access to your Direct Message and all of this messages will be safe for you .

				2. Information Security

				2.1 InProbes to care of your personal information tries that dear users have a good experience

				2.2 We use commercially reasonable methods to keep personally identifiable information securely in Our files and systems. We do not handle your Instagram passwords directly.

				2.3 Our databases are secured with passwords to guard against unauthorized access of Our systems.

				3. Information Sharing and Disclosure

				3.1 InProbes never provide your personal information to other organizations and individuals and also not rent unless whit warrant forced provide to Judicial authority.

				3.2 InProbes keeps for self the right to publish general and statistics information of a group of users for commercial and research purposes .It is obvious that this paragraph does not
				include your personal information .

				3.3 you can after the register in site shared your personal information through API whit Third party services.

				4. Our policy towards children Our Site is not directed to children under 13. If you become aware that your child has provided Us with personal information without your consent, please
				contact Us at info@inprobes.me. We do not knowingly collect personal information from children under 13 and if faced whit this terms we can immediately delete saved information in
				InProbes servers .

				5. Third Party Links and Advertising you may see advertising links to third party websites in your panel that InProbes have no responsibility to keep your information in this sites
				.also responsibility of content provided in this links is whit responsible of site.

				6. Questions and Suggestions If you have any questions or concerns about this Privacy Policy or its implementation you may contact Us at info@inprobes.me.

				7. Modifications to This Privacy Policy This Privacy Policy is subject to change at any time without notice. To make sure more, review it periodically.

				8. Miscellaneous

				8.1 user content will be stored in a database and after statistical calculations will be made available to them.

				8.2 Any change in the main account users in less than 24 hours the content stored in the database will be applied.

				8.3 you can access to information with last of update .

				8.4 user information updated regularly ,but any time you can update your account .

				8.5 For the purposes of service ,you cant post or remove comment directly from Instagram .

				8.6 users can unsubscribe at any time and exit system .

				8.7 information of users that unsubscribe stay on site until 90 days ,because if return again given to them and after this time clear information.</p>
				<br><br><br><br>
				<p style="font-weight:bold;"> Dec. 12, 2016, 9:11 a.m.</p>
			</div>
			<div class="col-md-2 col-xs-1 col-sm-1"></div>
		</div>
	</div>
</section>
{% endblock %}

templates/index/footer.html
{% load i18n %}
<section>
    <div class="col-md-12 bord-green">
        <div class="container">
            <div class="row">
                <div class="footer">
                <br><br>
                    <div class="col-md-4 col-xs-12 col-sm-12">
                        <div class="flo-right" style="margin-right:4%;">
                            <span id="subscribe-message" class="title"></span>
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                <button class="btn btn-outline-secondary btn-color" type="button" onclick="validateSubscribeEmail()">عضویت</button>
                                </div>
                                <input type="text" class="form-control dir-right" placeholder="لطفا ایمیل خود را وارد کنید" name="subscribe-email" id="subscribe-email" placeholder="آدرس ایمیل خود را وارد کنید" aria-label="" aria-describedby="basic-addon1">
                            </div>
                        </div>
                        <br><br>
                        <div class="social-div">
                            <ul class="point-ul social">
                                <li><a href="https://www.telegram.me/inprobes"><i class="fab fa-telegram fa-2x"></i></a></li>
                                <li><a href="https://www.instagram.com/inprobes"><i class="fab fa-instagram fa-2x"></i></a></li>
                                <li><a href="https://www.twitter.com/inprobes"><i class="fab fa-twitter fa-2x"></i></a></li>
                                <li><a href="https://www.linkedin.com/company/inprobes"><i class="fab fa-linkedin-in fa-2x"></i></a></li>
                                <li><a href="https://www.facebook.com/inprobes"><i class="fab fa-facebook fa-2x"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2 col-xs-12 col-sm-12">
                    </div>
                    <div class="col-md-6 col-xs-12 col-sm-12">
                        <div class="footer-feature">
                            <ul class="col-sm-6 point-ul">
                                <li><a href={% url 'page' slug="services" %}>سرویس ها</a></li>
                                <li><a href={% url 'page' slug="prices" %}>تعرفه ها</a></li>
                                <li><a href={% url 'page' slug="demo" %}>دریافت دمو</a></li>
                                <li><a href={% url 'page' slug="blog" %}>بلاگ</a></li>
                            </ul>
                            <ul class="col-sm-6 point-ul">
                                <li><a href={% url 'page' slug="faq" %}>سوالات متداول</a></li>
                                <li><a href={% url 'page' slug="contact-us" %}>تماس با ما</a></li>
                                <li><a href={% url 'page' slug="terms-of-service" %}>شرایط استفاده</a></li>
                                <li><a href={% url 'page' slug="privacy-policy" %}>حریم شخصی</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
        <br>
            <h4 class="mid-text">ساخته شده با <i class="fas fa-heart fa-x fa-feature"></i> در تهران</h4>
        </div>
    </div>
</section>

templates/index/register.html
{% extends 'index/base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %}
<title>{% trans "InProbes • Register" %}</title>
{% endblock %}
{% block meta%}
<meta name="description" content="{% blocktrans %}Analyze your Instagram account like professionals, manage Instagram campaigns and get dipper inside your audiences statistics{% endblocktrans %}">
<meta property="og:title" content='{% trans "InProbes • Register" %}'/>
<meta property="og:description" content="{% blocktrans %}Analyze your Instagram account like professionals, manage Instagram campaigns and get dipper inside your audiences statistics{% endblocktrans %}"/>
<meta property="og:image" content="https://inprobes.com/static/index/img/logo/social.png"/>
<meta name="keywords" content="Professional Instagram account analyzer, hold or manage campaigns with specific hashtags, audiences statistics">
{% endblock %}
{% block content %}
<section>
	<div class="col-md-12 col-xs-12 col-sm-12">
		<div class="container">
			<div class="row text-center">
				<br>
				<div class="col-md-3 col-sm-2 col-xs-2"></div>
				<div class="col-md-6 col-xs-8 col-sm-8 login-feat">
					<img src='{% static "index/image/inprobes-2color.png" %}' class="img-fluid responsive " alt="inprobes">
					<h4 class="section-heading dir-right">{{context.banner|safe}}</h4>
					{% if context.show_register_form %}
					<form role='form' class="form-login dir-right" action='' method='POST' id='register_form' enctype='multipart/form-data'>
						{% csrf_token %}
						<div class="form-group">
							<input id="id_fullname" name="fullname" class="form-control input-pad" type="text" placeholder="نام کامل">
							{% if user_form.fullname.errors %}
							{% for error in user_form.fullname.errors %}
							<h5 style='color:#940037;'>
								{% trans error %}
							</h5>
							{% endfor %}
							{% endif %}
						</div>
						<div class="form-group">
							<input id="id_username" name="username" class="form-control input-pad" type="text" placeholder="نام کاربری">
							{% if user_form.username.errors %}
							{% for error in user_form.username.errors %}
							<h5 style='color:#940037;'>
								{% trans error %}
							</h5>
							{% endfor %}
							{% endif %}
						</div>
						<div class="form-group">
							<input id="id_email" name="email" class="form-control input-pad" type="text" placeholder="ایمیل">
							{% if user_form.email.errors %}
							{% for error in user_form.email.errors %}
							<h5 style='color:#940037;'>
								{% trans error %}
							</h5>
							{% endfor %}
							{% endif %}
						</div>
						<div class="form-group">
							<input id="id_password" name="password" class="form-control input-pad" type="password" placeholder="رمز عبور">
							{% if user_form.password.errors %}
							{% for error in user_form.password.errors %}
							<h5 style='color:#940037;'>
								{% trans error %}
							</h5>
							{% endfor %}
							{% endif %}
						</div>
						<button class="btn btn-default btn-submit" type="submit">ثبت نام</button>
					</form>

					<div class="mt-3 f-16">
						<p style="color:#000;">اکانت اینپروبز دارید؟ <a class="login-a" href='{% url "user_login" %}'>از اینجا وارد شوید</a></p>
					</div>
					{% endif %}
				</div>
				<div class="col-md-3 col-sm-2 col-xs-2"></div>
			</div>
		</div>
	</div>
</section>
{% endblock %}