blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
    url(r'^category/(?P<cat>.*)$', views.blog_list, name='blog_post_list_cat'),
    url(r'^tag/(?P<tag>.*)$', views.blog_list, name='blog_post_list_tag'),
    url(r'^archive/year/(?P<year>\d{4})/month/(?P<month>\d{1,2})$',
        views.blog_list, name='blog_post_list_year_month'),
    url(r'^archive/year/(?P<year>\d{4})$', views.blog_list,
        name='blog_post_list_year'),
    url(r'^post/(?P<slug>.*)/$', views.single_post, name='blog_single'),
    url(r'^$', views.blog_list, name="blog_post_list"),
]

dashboard/api/urls.py
from django.conf.urls import url
from dashboard.api import views


urlpatterns = [
    url(r'^set_facebook_account/$', views.set_facebook_account, name='set_facebook_account'),
    url(r'^save_instagram_data/$', views.save_instagram_data, name='save_instagram_data'),
    url(r'^select_account/(?P<ig_ac_id>[0-9].*)/$', views.select_account, name='select_account'),
    url(r'^get_accounts/$', views.get_accounts, name='get_accounts'),
    url(r'^get_progress/$', views.get_progress, name='get_progress'),
]

dashboard/urls.py
from django.conf.urls import url, include

from dashboard import views

urlpatterns = [
    url(r'^api/', include('dashboard.api.urls')),
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^profile/$', views.profile_settings, name='profile_settings'),
    url(r'^hashtag/$', views.hashtag_campaign, name='hashtag_campaign'),
    url(r'^hashtag/create/$', views.create_hashtag, name='create_hashtag'),
    url(r'^comment/$', views.comment_campaign, name='comment_campaign'),
    url(r'^comment/create/$', views.create_comment, name='create_comment_step_1'),
    url(r'^comment/create/(?P<pid>[0-9]+)/$', views.create_comment, name='create_comment_step_2'),
]

home/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.sitemaps.views import sitemap

from solid_i18n.urls import solid_i18n_patterns

from home.sitemaps import PagesSitemap, StaticSitemap, BlogSitemap


sitemaps = {
    'pages': PagesSitemap(),
    'static': StaticSitemap(),
    'blog': BlogSitemap(),
}
urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^secureadmin/', admin.site.urls),
    url(r'^redactor/', include('redactor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns.append(
        url(r'^rosetta/', include('rosetta.urls')),
    )

urlpatterns += solid_i18n_patterns(
    url(r'^account/', include('account.urls')),
    url(r'^financial/', include('financial.urls')),
    url(r'^payment/', include('payment.urls')),
    url(r'^report/', include('report.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^support/', include('tickets.urls')),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^', include('index.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
)

dashboard/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

index/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.html import format_html
from django.utils.translation import ugettext_lazy as _

from ckeditor.fields import RichTextField

from services.InstagramData.models import User as insta_user
from services.graph_api.models import Account


class Page(models.Model):
    header = models.CharField(max_length=255)
    body = RichTextField()
    meta_desc = models.TextField(
        blank=True,
        help_text="Meta description of page, max length to 160 character"
    )
    created = models.DateTimeField(auto_created=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = _('Page')
        verbose_name_plural = _('Pages')

    def __unicode__(self):
        return self.header

    def save(self, *args, **kwargs):
        super(Page, self).save(*args, **kwargs)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('page', args=[self.slug])


class UserProfile(models.Model):
    """Relation with django User that imported at top"""
    LOW = 'L'
    MEDIUM = 'M'
    HIGH = 'H'

    LEVELS = (
        (LOW, _('Low')),
        (MEDIUM, _('Medium')),
        (HIGH, _('High'))
    )
    user = models.OneToOneField(User)

    fullname = models.CharField(verbose_name=_('fullname'), max_length=10,
                                blank=True)
    level = models.CharField(verbose_name=_('level'), choices=LEVELS,
                             max_length=1, default='L')
    website = models.URLField(verbose_name=_('website'), blank=True)
    mobile = models.CharField(verbose_name=_('mobile'), max_length=255,
                              blank=True)
    profile_pic = models.ImageField(verbose_name=_('profile_pic'),
                                    upload_to='profile_pics', blank=True)
    instagram_id = models.ForeignKey(insta_user, blank=True, null=True)
    accounts = models.ManyToManyField(Account, through='InstagramAccounts')
    confirm = models.BooleanField(default=False)
    parsed = models.BooleanField(default=False)

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __unicode__(self, *args):
        return self.user.username

    @property
    def has_instagram(self):
        return self.instagram_id is not None

    @property
    def has_facebook(self):
        return self.facebook_tokens.filter(valid=True).exists()

    @property
    def facebook_token(self):
        token = self.facebook_tokens.filter(valid=True).last()
        if token:
            return token.access_token

    @property
    def has_instagram_account(self):
        return self.instagram_accounts.filter(status=True).exists()

    @property
    def primary_account(self):
        account = self.instagram_accounts.filter(status=True, primary=True)
        return account.first()

    def expire_facebook_token(self):
        """When api face 400 status then facebook token should be expired"""
        token = self.facebook_token.filter(valid=True).last()
        token.valid = False
        token.save()

    def make_parsed(self):
        self.parsed = True
        self.save()

    def email(self):
        return self.user.email

    def bio(self):
        if self.instagram_id:
            return self.instagram_id.bio
        else:
            return None

    def joined_at(self):
        if self.instagram_id:
            return self.instagram_id.added
        else:
            return None

    def media_count(self):
        if self.instagram_id:
            return self.instagram_id.media
        else:
            return None

    def avatar(self):
        if self.instagram_id:
            return format_html(
                '<img src="{}" style="height: 40px;width: 40px;"/>',
                self.instagram_id.profile_picture)
        else:
            return self.profile_pic

    @classmethod
    def confirm_user(cls, user_id):
        user = User.objects.get(id=user_id)
        if user:
            user.userprofile.confirm = True
            user.userprofile.save()
            return True
        return False

    @classmethod
    def set_parsed(cls, user_id):
        """Call this method when media cached and parsed for the first time"""
        user = User.objects.get(id=user_id)
        if user:
            user.userprofile.parsed = True
            user.userprofile.save()
            return True
        return False

    @classmethod
    def load(cls, user_id):
        user = User.objects.get(id=user_id)
        return user.userprofile

    @classmethod
    def add_instagram_account(cls, user_id, instagram_user):
        profile = cls.load(user_id)
        profile.instagram_id = instagram_user
        profile.save()

    def set_instageram_id_to_null(self):
        """IF handler face an access token error should remove instagram_id
        to force user for setting new instagram account"""
        self.instagram_id = None
        self.parsed = False
        self.save()

    def update_level(self, level):
        self.level = level
        self.save()

    def has_analytic_permission(self):
        purchases = self.user.purchase.filter(valid=True)
        current = any([purchase.is_valid for purchase in purchases])
        if self.instagram_id.is_free:
            return True
        if self.level == self.LOW:
            return False
        return current

    def can_add_hashtag(self):
        limit = {'H': 5, 'M': 3, 'L': 0}
        return self.hashtag_reports.filter(active=True).count() < limit[self.level]


class FacebookCredentials(models.Model):
    expires_in = models.IntegerField()
    data_access_expirations_time = models.IntegerField()
    user_id = models.BigIntegerField()
    access_token = models.TextField()
    signed_request = models.TextField()

    profile = models.ForeignKey(UserProfile, related_name='facebook_tokens')

    valid = models.BooleanField(default=True)

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return '{} => {}'.format(self.profile, self.valid)


class InstagramAccounts(models.Model):
    profile = models.ForeignKey(UserProfile, related_name='instagram_accounts')
    account = models.ForeignKey(Account, related_name='profile')
    date_added = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)
    primary = models.BooleanField(default=False)

    def __unicode__(self):
        return '{} > {}'.format(self.profile, self.account)

    def save(self, **kwargs):
        primary = InstagramAccounts.objects.filter(
                profile=self.profile, status=True, primary=True
        ).exists()
        self.primary = self.status and (not primary)
        return super(InstagramAccounts, self).save(**kwargs)

dashboard/api/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from index.models import FacebookCredentials, InstagramAccounts
from services.graph_api.models import Account
from services.graph_api.tasks import graph_media_updater


@login_required
def set_facebook_account(request):
    data = json.loads(request.body)
    if data['status'] == 'connected':
        auth = data['authResponse']
        cred, result = FacebookCredentials.objects.get_or_create(
            expires_in=auth['expiresIn'], user_id=auth['userID'],
            data_access_expirations_time=auth['data_access_expiration_time'],
            access_token=auth['accessToken'], profile=request.user.userprofile,
            signed_request=auth['signedRequest'],
        )
    return JsonResponse(data)


@login_required
def save_instagram_data(request):
    data = json.loads(request.body)
    acid = data.pop('id')
    account, result = Account.objects.update_or_create(id=acid, defaults=data)
    account_profile, result = InstagramAccounts.objects.get_or_create(
        account=account, profile=request.user.userprofile
    )
    return JsonResponse({"status": "ok"})


@login_required
def get_accounts(request):
    accounts = InstagramAccounts.objects.select_related('account').filter(
        profile=request.user.userprofile
    )
    primary = request.user.userprofile.primary_account is not None
    response = [{'account': {
        'username': a.account.username, 'biography': a.account.biography,
        'website': a.account.website, 'name': a.account.name,
        'profile_picture': a.account.profile_picture_url,
        'media_count': a.account.media_count,
        'followers_count': a.account.followers_count,
        'follows_count': a.account.follows_count
    }, 'status': a.status, 'set_link': a.id} for a in accounts]
    return JsonResponse(dict(accounts=response, primary=primary))


@login_required
def select_account(request, ig_ac_id):
    instagram_account = get_object_or_404(InstagramAccounts, pk=ig_ac_id)
    instagram_account.status = True
    instagram_account.save()
    graph_media_updater.delay(request.user.id)
    return JsonResponse(
        {'status': 'ok', 'acid': ig_ac_id, 'user': request.user.username}
    )


@login_required
def get_progress(request):
    profile = request.user.userprofile
    account = profile.primary_account
    response = dict(media_count=0, current_count=0, percentage=0)
    if account is not None:
        response = dict(
            media_count=int(account.account.media_count),
            current_count=account.account.posts.filter(partial=False).count()
        )
        if response['media_count'] == 0:
            rate = 1
        elif response['current_count'] == 0:
            rate = 0
        else:
            rate = response['media_count'] / response['current_count']
        response['percentage'] = rate * 100
    return JsonResponse(response)


# TODO: Exchange short_trem access_token to a long_term:
# https://developers.facebook.com/docs/facebook-login/access-tokens/refreshing

templates/index/dashboard/widgets/account_stat.html
{% load i18n %}
<div class="row">
    <div class="panel-top">

      <div class="col-md-5 col-sm-10 col-xs-11">
        <div class="sections post-section">
          <center>
            <p class="title-text">پست‌ها</p>
          </center>
          <div class="post-box">
              <div class="col-md-4 col-sm-4 col-xs-4">
              <center>
                <i class="far fa-file-image fa-3x fa-orange"></i>
                <p class="top-design">{{context.type.images}}</p>
              </center>
            </div>
              <div class="col-md-4 col-sm-4 col-xs-4">
              <center>
                <i class="far fa-file-video fa-3x fa-orange"></i>
                <p class="top-design">{{context.type.videos}}</p>
              </center>
            </div>
            <div class="col-md-4 col-sm-4 col-xs-4">
              <center>
                <i class="fas fa-clone fa-3x fa-orange"></i>
                <p class="top-design">{{context.type.carousel}}</p>
                </center>
            </div>

          </div>
        </div>
      </div>

      <div class="col-md-5 col-sm-10 col-xs-11">
        <div class="like-section">
            <center>
              <i class="fas fa-heart fa-3x fa-red"></i>
            </center>
            <div class="col-md-6 col-xs-6 col-sm-6">
              <center class="">
                <p class="detail-left">میانگین</p>
                <p class="detail-left">{{context.like.avg|floatformat}}</p>
              </center>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6">
              <center>
                <p class="detail-right">مجموع</p>
                <p class="detail-right">{{context.like.sum}}</p>
            </center>
            </div>
        </div>
        <div class="comment-section">
              <center>
            <span class="">
              <i class="fas fa-comment fa-3x fa-blue"></i>
            </span>
            </center>
            <div class="col-md-6 col-xs-6 col-sm-6">
              <center>
                <p class="detail-left">میانگین</p>
                <p class="detail-left">{{context.comment.avg|floatformat}}</p>
              </center>
            </div>
            <div class="col-md-6 col-xs-6 col-sm-6">
              <center>
                <p class="detail-right">مجموع</p>
                <p class="detail-right">{{context.comment.sum}}</p>
              </center>
            </div>
        </div>
      </div>

      <div class="col-md-2 col-sm-10 col-xs-11">
        <div class="sections">
          <center>
              <i class="fas fa-users fa-3x fa-green"></i>
              <div class="follow-section">
                <div>
                  <p>دنبال می‌کنید:</p>
                  <p>{{context.relation.following}}</p>
                </div>
                <hr class="hr-cust">
                <div>
                  <p>دنبال کننده:</p>
                  <p>{{context.relation.followers}}</p>
                </div>
            </div>
          </center>
        </div>
      </div>


    </div>
  </div>

templates/index/dashboard/widgets/hashtag_cards.html
<div class="create-new">
  <a type="button" href="{% url 'create_hashtag' %}" class="btn-campaign btn-green-campaign">هشتگ جدید</a>
  <!--<a type="button" href="{% url 'create_hashtag' %}" class="btn-campaign btn-green-campaign">مشاهده کمپین‌ یا مسابقه‌های فعال</a>-->
  <!--<a type="button" href="{% url 'create_hashtag' %}" class="btn-campaign btn-green-campaign">کمپین جدید</a>-->
</div>
<div class='row'>
{% for report in context.reports %}
  <div class="col-md-6 col-xs-12 col-sm-12 col-lg-6">
      <div class="campaign-detail">
        {% if report.active %}
          <span class="label-detail label-active">فعال</span>
        {% else %}
          <span class="label-detail label-inactive">غیر فعال</span>
        {% endif %}
        <p class="camp-h2">{{report.hashtag}}</p>
        <hr class="hr-camp">
        <div class="col-md-4 col-xs-3 col-sm-3 col-lg-4 top-detail">
          <p class="camp-p">پست‌ها   </p>
          <p class="camp-p">{{report.media_count}}</p>
        </div>
        <div class="col-md-4 col-xs-4 col-sm-4 col-lg-4 top-detail">
          <p class="camp-p">مشارکت ‌کنندگان</p>
          <p class="camp-p">{{report.participants|length}}</p>
        </div>
        <div class="col-md-4 col-xs-5 col-sm-5 col-lg-4 top-detail">
          <p class="camp-p">هشتگ‌های همراه</p>
          <p class="camp-p">{{report.relevant_tags.count}}</p>
        </div>
        <div class="col-md-6 col-xs-12 col-sm-12 col-lg-6">
          <center>
            <a type="button" href="{% url 'hashtags_hashtag_analytics' report.id %}" class="btn-campaign btn-gradient-campaign">تحلیل کمپین شما</a>
          </center>
        </div>
        <div class="col-md-6 col-xs-12 col-sm-12 col-lg-6">
          <center>
            <a type="button" href="{% url 'hashtags_post_list' report.id %}" class="btn-campaign btn-gradient-campaign">مشاهده پست‌ها</a>
          </center>
        </div>
      </div>
    </div>
{% endfor %}
{% if not context.reports.count|divisibleby:2 %}
  <div class="col-md-6 col-xs-12 col-sm-12 col-lg-6">
    <div class="create-new-campaign">
      <p class="plus-detail"><a href="{% url 'create_hashtag' %}" class="a-detail"><i class="fas fa-plus fa-7x"></i></a></p>
      <div class="desc-campaign">
        <p>همین الان هشتگ مورد نظر خود را از این قسمت تعریف کنید. اینجا می‌توانید کمپین خود را مدیریت کنید و گزارش لحظه‌ای رو بگیرید.</p>
      </div>
    </div>
  </div>
{% endif %}
</div>

templates/index/dashboard/widgets/inactive_alert.html
<div class="alert alert-danger">
    هشدار: باتوجه به تغییر سیاست‌های اینستاگرام تحلیل‌های حساب‌های کاربری بروز نخواهند شد. در حال طراحی سرویس جدید هستیم و به محض اتمام مراحل آماده سازی شما را مطلع می‌کنیم. برای اطلاعات بیشتر  <a href="http://inprobes.com/blog/post/why-instagram-api-shutdown-immediately/" class="alert-link">این پست را بخوانید</a>.
</div>

templates/index/dashboard/widgets/messages_section.html
{% for message in messages %}
<div class="alert alert-{{message.tags}}">
	<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
	{{message}}
</div>
{% endfor %}

templates/index/dashboard/widgets/nav_side.html
{% load i18n %}
{% load staticfiles %}
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
				    <li class="text-center">
                        {% if request.user.userprofile.profile_pic %}
                            <img src='{{request.user.userprofile.profile_pic.url}}' class="user-image img-responsive"/>
                        {% elif request.user.userprofile.instagram_id %}
                            <img src="{{request.user.userprofile.instagram_id.profile_picture}}" class="user-image img-responsive">
                        {% else %}
                            <img src='{% static "index/assets/img/find_user.png" %}' class="user-image img-responsive" />
                        {% endif %}
					</li>
				    <li class='text-center'>
                        <!--<h4 style="color: white;">{{request.user.get_full_name|title}}</h4>-->
                        {% if request.user.userprofile.instagram_id %}
                            <h5 style="color: white;">{{request.user.userprofile.instagram_id.username}} <i class="fab fa-instagram" aria-hidden="true"></i> </h5>
                        {% else %}
                            <h5 style="color: white;">@{{request.user.username}}</h5>
                        {% endif %}
                        <h5 style="color: #00945d;"> پنل {{profile.get_level_display}}</h5>
                    </li>
                    <li>
                        <a class="{% ifequal context.nav_bar_side 'dashboard' %}active-menu{% endifequal %}" href="{% url 'dashboard' %}">
                            <i class="fas fa-tachometer-alt fa-2x"></i>{% trans 'Dashboard' %}
                        </a>
                    </li>
                    {% if profile.confirm and profile.has_instagram and profile.parsed %}
                    <li>
                        <a class="{% ifequal context.nav_bar_side 'analytic'%}active-menu{% endifequal %}" href="{% url 'analytic'%}">
                            <i class="fas fa-chart-bar fa-2x"></i> {% trans "Analytics" %}
                        </a>
                    </li>

                    <li>
                        <a class="{% ifequal context.nav_bar_side 'post_list' %}active-menu{% endifequal %}" href="{% url 'post_list'%}">
                            <i class="fa fa-th-large fa-2x" aria-hidden="true"></i>{% trans 'Posts'%}
                        </a>
                    </li>

                    <li>
                        <a class="{% ifequal context.nav_bar_side 'hashtags' %}active-menu{% endifequal %}" href="{% url 'hashtags'%}">
                            <i class="fas fa-hashtag fa-2x" aria-hidden="true"></i>{% trans 'Hashtags'%}
                        </a>
                    </li>

                    <li>
                        <a class="{% ifequal context.nav_bar_side 'financial' %}active-menu{%endifequal%}" href='{% url "financial" %}'>
                            <i class="fa fa-credit-card fa-2x"></i> {% trans "Financial"%}
                        </a>
                    </li>	

                    {% endif %}
                    <li>
                        <a class="{% ifequal context.nav_bar_side 'support'%}active-menu{%endifequal%}" href='{% url "support" %}'>
                            <i class="fa fa-envelope fa-2x"></i> {% trans "Support" %}
                        </a>
                    </li>
                    <li>
                        <a class="{% ifequal context.nav_bar_side 'settings' %}active-menu{%endifequal%}" href='{% url "settings" %}'>
                            <i class="fa fa-laptop fa-2x"></i> {% trans "Settings"%}
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

templates/index/dashboard/widgets/nav_top.html
{% load i18n %}
{% load staticfiles %}
{% load custom_tags %}
<nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'dashboard' %}">
            <center>
            <img src="{% static 'index/assets/img/inprobes-typo-full.png' %}" alt='logo' width='170'>
            </center>
        </a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-c-menu">
            <li>
                <div style='padding: 15px;'>
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% get_current_language as current_lang %}
                    <form action='{% url "set_language" %}' method='POST'>{% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}" />
                        {% for lang in languages %}
                            {% ifnotequal lang.code current_lang %}
                            <input type='hidden' name='language' value='{{lang.code}}'/>
                            <button class='btn btn-general' type='submit' value='{{lang.code}}'>{{lang.name_local}} <i class="fa fa-globe" aria-hidden="true"></i></button>
                            {% endifnotequal %}
                        {% endfor %}
                    </form>
                    <a href="{% url 'user_logout' %}" class="btn btn-danger logout-btn square-btn-adjust">خروج</a>

                </div>
            </li>
        </ul>
    </div>
</nav>

templates/index/dashboard/widgets/popular_table.html
{% load i18n %}
{% load l10n %}
<div class="panel panel-default">
    <div class="panel-heading">
       <center>{% blocktrans %}The Most Popular Posts(by likes){% endblocktrans %}</center>
    </div>
    <div class="panel-body">
        {% for media in context.table %}
            <div class="col-md-3 col-sm-4 col-xs-6 post-tile">
                <center>
                    <a data-toggle="modal" data-target="#{{media.images.id}}">
                        <img src="{{media.images.thumbnail}}" class="img-rounded img-responsive">
                    </a>
                    <i class="fa fa-heart"></i> {{media.like_count}} |
                    <i class="fa fa-comments"></i> {{media.comment_count}}
                </center>
            </div>
            <div class="modal fade" id="{{media.images.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        </div>
                        <div class="modal-body">
                            <div class="row">
                                <div class='col-md-7'>
                                    <img src="{{media.images.low_resolution}}" class="img-responsive">
                                </div>
                                <div class='col-md-5'>
                                    <table class='table'>
                                        <tbody>
                                        <tr><td><i class="fa fa-heart" aria-hidden="true"></i>{% trans 'Likes' %}</td><td><span class="badge">{{media.like_count}}</span></td></tr>
                                        <tr><td><i class="fa fa-comments" aria-hidden="true"></i>{% trans 'Comments' %}</td><td><span class="badge">{{media.comment_count}}</span></td></tr>
                                            <tr><td><i class="fa fa-tags" aria-hidden="true"></i>{% trans 'Tags' %}</td><td><span class="badge">12</span></td></tr>
                                            {% if media.location %}
                                        <tr><td><i class="fa fa-location-arrow" aria-hidden="true"></i>{% trans 'Location' %}</td><td><span class="badge">{{media.location}}</span></td></tr>
                                            {% endif %}
                                        <tr><td><i class="fa fa-users" aria-hidden="true"></i>{% trans 'Users in' %}</td><td><span class="badge">**</span></td></tr>
                                        <tr><td><i class="fa fa-clock-o" aria-hidden="true"></i>{% trans 'Time' %}</td><td><span class="badge">{{media.created_time|date:'Y M d D'}}</span></td></tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <hr>
                            <p>{{media.caption.text}}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

templates/index/dashboard/widgets/pt_notifications.html
{% load i18n %}
{% load custom_tags %}
		<div class="row">
			<div class='col-md-12 col-sm-12 col-xs-12'>
				<hr class="panel-hr">
				<div class='col-md-4 col-xs-12 col-sm-6'>
					<div class="panel panel-primary text-center no-boder bg-color-note4">
						<div class="panel-body">
							{% blocktrans with avg=context.pt_notes.max_post.avg ranges=context.pt_notes.max_post.ranges|elements %}
							<p>In {{ranges}} time period had the most post sent with {{avg}} average </p>
							{% endblocktrans %}
						</div>
					</div>
					<div class="panel panel-primary text-center no-boder bg-color-note3">
						<div class="panel-body">
							{% blocktrans with avg=context.pt_notes.min_post.avg ranges=context.pt_notes.min_post.ranges|elements %}
							<p>Only {{avg}} post had been sent between {{ranges}} </p>
							{% endblocktrans %}
						</div>
					</div>
				</div>
				<div class='col-md-4 col-xs-12 col-sm-6'>
					<div class="panel panel-primary text-center no-boder bg-color-note4">
						<div class="panel-body">
							{% blocktrans with avg=context.pt_notes.max_like.avg ranges=context.pt_notes.max_like.ranges|elements %}
							<p>In {{ranges}} time period had the most welcome, with {{avg}} like average</p>
							{% endblocktrans %}
						</div>
					</div>
					<div class="panel panel-primary text-center no-boder bg-color-note3">
						<div class="panel-body">
							{% blocktrans with avg=context.pt_notes.min_like.avg ranges=context.pt_notes.min_like.ranges|elements %}
							<p>In {{ranges}} time period had the least welcome, with {{avg}} like average</p>
							{% endblocktrans %}
						</div>
					</div>
				</div>
				<div class='col-md-4 col-xs-12 col-sm-6'>
					<div class="panel panel-primary text-center no-boder bg-color-note4">
						<div class="panel-body">
							{% blocktrans with avg=context.pt_notes.max_comment.avg ranges=context.pt_notes.max_comment.ranges|elements %}
							<p>In {{ranges}} time period had recieved the most feedback with average of {{avg}} comments in each post </p>
							{% endblocktrans %}
						</div>
					</div>
					<div class="panel panel-primary text-center no-boder bg-color-note3">
						<div class="panel-body">
							{% blocktrans with avg=context.pt_notes.min_comment.avg ranges=context.pt_notes.min_comment.ranges|elements %}
							<p>In {{ranges}} time period with average of {{avg}} comments in each post, had recieved the least feedback</p>
							{% endblocktrans %}
						</div>
					</div>
				</div>
			</div>
		</div>